import { Resend } from "resend";
import { buildInvoiceEmailTemplate } from "./invoiceEmail.template";
import { sendTelegramMessage } from "@/lib/telegram";
import { getSharedIntegration } from "@/lib/centralApiRead";
import { renderEmailTemplate } from "@/core/email/renderEmailTemplate";
import { connectDB } from "@/lib/mongodb";

/**
 * Central-api is now the ONLY source for Resend credentials -- per
 * explicit direction, every integration is managed centrally, full stop.
 * This app's local Integration{provider:"EMAIL"} model is no longer read
 * here (a business that wants its own sender identity gets that via a
 * business-specific override on central-api's dashboard instead -- see
 * routes/integrations.js's businessId-scoped GET/PUT). RESEND_API_KEY/
 * RESEND_FROM env vars remain only as a last-resort safety net for a
 * central-api outage, never the primary source.
 */
async function resolveResendCreds(businessId?: string): Promise<{ apiKey: string; from: string }> {
  const shared = await getSharedIntegration<{ apiKey?: string; fromEmail?: string }>("RESEND", businessId);
  if (shared?.apiKey) {
    return { apiKey: shared.apiKey, from: shared.fromEmail || process.env.RESEND_FROM || "" };
  }

  if (!process.env.RESEND_API_KEY) {
    sendTelegramMessage(
      "🚨 <b>No Resend API key configured</b> (central-api shared integration, and no local RESEND_API_KEY fallback either) — every email send is failing right now."
    ).catch(() => {});
  }

  return {
    apiKey: process.env.RESEND_API_KEY || "",
    from: process.env.RESEND_FROM || "",
  };
}

/**
 * Password-reset link email. Kept deliberately minimal (no invoice-style
 * template dependency) -- resetUrl is single-use/time-boxed, generated by
 * api/auth/reset-password/request/route.ts.
 */
export async function sendPasswordResetEmail({
  to,
  resetUrl,
  businessId,
}: {
  to: string;
  resetUrl: string;
  businessId?: string;
}) {
  try {
    await connectDB();
    const override = await renderEmailTemplate("FORGOT_PASSWORD", { resetUrl });
    if (override === "disabled") return { success: false, error: "Occasion disabled by admin" };

    const { apiKey, from } = await resolveResendCreds(businessId);
    if (!apiKey) {
      throw new Error("No Resend API key configured (neither business-specific nor global RESEND_API_KEY)");
    }
    const resend = new Resend(apiKey);

    const result = await resend.emails.send({
      from,
      to,
      subject: override?.subject || "Reset your password",
      html: override?.html || `
        <p>We received a request to reset your password.</p>
        <p><a href="${resetUrl}">Click here to reset your password</a>. This link expires in 30 minutes.</p>
        <p>If you didn't request this, you can safely ignore this email.</p>
      `,
    });

    return { success: true, result };
  } catch (err: any) {
    console.error("RESEND PASSWORD RESET EMAIL ERROR", err);
    return { success: false, error: err?.message || "Unknown email error" };
  }
}

/**
 * Generic email-verification OTP -- used by any public/unauthenticated flow
 * that needs to confirm a real email address before accepting a submission
 * (currently: the public appointment-request page). Deliberately separate
 * from sendAgreementOtpEmail, which is purpose-built for signing an
 * agreement and carries agreement-specific copy/context.
 */
export async function sendVerificationOtpEmail({
  to,
  otp,
  purpose,
  businessId,
}: {
  to: string;
  otp: string;
  purpose: string;
  businessId?: string;
}) {
  try {
    await connectDB();
    const override = await renderEmailTemplate("VERIFICATION_OTP", { otp, purpose });
    if (override === "disabled") return { success: false, error: "Occasion disabled by admin" };

    const { apiKey, from } = await resolveResendCreds(businessId);
    if (!apiKey) {
      throw new Error("No Resend API key configured (neither business-specific nor global RESEND_API_KEY)");
    }
    const resend = new Resend(apiKey);

    const result = await resend.emails.send({
      from,
      to,
      subject: override?.subject || `Your verification code: ${otp}`,
      html: override?.html || `
        <p>Your verification code for ${purpose} is:</p>
        <p style="font-size:28px;font-weight:700;letter-spacing:4px;">${otp}</p>
        <p>This code is valid for 10 minutes. If you didn't request this, you can ignore this email.</p>
      `,
    });

    return { success: true, result };
  } catch (err: any) {
    console.error("RESEND VERIFICATION OTP EMAIL ERROR", err);
    return { success: false, error: err?.message || "Unknown email error" };
  }
}

/** Newsletter subscription welcome email -- best-effort, non-fatal (see caller). */
export async function sendNewsletterWelcomeEmail({
  to,
  businessId,
}: {
  to: string;
  businessId?: string;
}) {
  try {
    await connectDB();
    const override = await renderEmailTemplate("NEWSLETTER_WELCOME", {});
    if (override === "disabled") return { success: false, error: "Occasion disabled by admin" };

    const { apiKey, from } = await resolveResendCreds(businessId);
    if (!apiKey) {
      throw new Error("No Resend API key configured (neither business-specific nor global RESEND_API_KEY)");
    }
    const resend = new Resend(apiKey);

    const result = await resend.emails.send({
      from,
      to,
      subject: override?.subject || "You're subscribed!",
      html: override?.html || `<p>Thanks for subscribing -- we'll keep you posted on new products and offers.</p>`,
    });

    return { success: true, result };
  } catch (err: any) {
    console.error("RESEND NEWSLETTER EMAIL ERROR", err);
    return { success: false, error: err?.message || "Unknown email error" };
  }
}

/** Agreement e-signature OTP email. The OTP itself must never be returned
 * in an API response -- see api/agreements/[id]/otp/route.ts's fix comment. */
export async function sendAgreementOtpEmail({
  to,
  partyName,
  agreementTitle,
  otp,
  signingLink,
  businessId,
}: {
  to: string;
  partyName: string;
  agreementTitle: string;
  otp: string;
  signingLink?: string;
  businessId?: string;
}) {
  try {
    await connectDB();
    const override = await renderEmailTemplate("AGREEMENT_OTP", { partyName, agreementTitle, otp, signingLink: signingLink || "" });
    if (override === "disabled") return { success: false, error: "Occasion disabled by admin" };

    const { apiKey, from } = await resolveResendCreds(businessId);
    if (!apiKey) {
      throw new Error("No Resend API key configured (neither business-specific nor global RESEND_API_KEY)");
    }
    const resend = new Resend(apiKey);

    const result = await resend.emails.send({
      from,
      to,
      subject: override?.subject || `Action required: sign "${agreementTitle}"`,
      html: override?.html || `
        <p>Dear ${partyName},</p>
        <p>You have been requested to sign the agreement "${agreementTitle}".</p>
        ${signingLink ? `<p><a href="${signingLink}">Click here to review and sign</a></p>` : ""}
        <p>Your OTP to verify your identity and sign is: <b>${otp}</b></p>
        <p>This OTP is valid for 30 minutes.</p>
      `,
    });

    return { success: true, result };
  } catch (err: any) {
    console.error("RESEND AGREEMENT OTP EMAIL ERROR", err);
    return { success: false, error: err?.message || "Unknown email error" };
  }
}

/** Registration welcome email -- best-effort, non-fatal (see callers). */
export async function sendWelcomeEmail({
  to,
  name,
  businessId,
}: {
  to: string;
  name: string;
  businessId?: string;
}) {
  try {
    await connectDB();
    const override = await renderEmailTemplate("WELCOME_REGISTRATION", { name });
    if (override === "disabled") return { success: false, error: "Occasion disabled by admin" };

    const { apiKey, from } = await resolveResendCreds(businessId);
    if (!apiKey) {
      throw new Error("No Resend API key configured (neither business-specific nor global RESEND_API_KEY)");
    }
    const resend = new Resend(apiKey);

    const result = await resend.emails.send({
      from,
      to,
      subject: override?.subject || "Welcome to AN Group",
      html: override?.html || `
        <p>Hi ${name},</p>
        <p>Your account has been created successfully. You can now sign in and get started.</p>
      `,
    });

    return { success: true, result };
  } catch (err: any) {
    console.error("RESEND WELCOME EMAIL ERROR", err);
    return { success: false, error: err?.message || "Unknown email error" };
  }
}

/** Sent when an admin/vendor creates a login for someone else with an
 * admin-assigned temporary password -- pairs with mustChangePassword: true
 * set on the User doc, so the recipient is prompted to change it on first
 * login. Best-effort, non-fatal (see callers). */
export async function sendAccountCredentialsEmail({
  to,
  name,
  loginUrl,
  tempPassword,
  businessId,
}: {
  to: string;
  name: string;
  loginUrl?: string;
  tempPassword?: string;
  businessId?: string;
}) {
  try {
    await connectDB();
    const override = await renderEmailTemplate("ACCOUNT_CREDENTIALS", { name, email: to, tempPassword: tempPassword || "", loginUrl: loginUrl || "" });
    if (override === "disabled") return { success: false, error: "Occasion disabled by admin" };

    const { apiKey, from } = await resolveResendCreds(businessId);
    if (!apiKey) {
      throw new Error("No Resend API key configured (neither business-specific nor global RESEND_API_KEY)");
    }
    const resend = new Resend(apiKey);

    const result = await resend.emails.send({
      from,
      to,
      subject: override?.subject || "Your AN Group account is ready",
      html: override?.html || `
        <p>Hi ${name},</p>
        <p>An account has been created for you on AN Group.</p>
        <p>Login email: <b>${to}</b></p>
        ${tempPassword ? `<p>Temporary password: <b>${tempPassword}</b></p>` : ""}
        ${loginUrl ? `<p><a href="${loginUrl}">Click here to sign in</a>.</p>` : ""}
        <p>You'll be asked to set a new password the first time you sign in.</p>
      `,
    });

    return { success: true, result };
  } catch (err: any) {
    console.error("RESEND ACCOUNT CREDENTIALS EMAIL ERROR", err);
    return { success: false, error: err?.message || "Unknown email error" };
  }
}

export async function sendInvoiceEmail({
  to,
  customerName,
  invoiceNumber,
  pdfUrl,
  grandTotal,
  orderId,
  businessId,
}: any) {
  try {

    console.log("RESEND EMAIL START", {
      to,
      invoiceNumber,
      orderId,
      businessId,
    });

    const { apiKey, from } = await resolveResendCreds(businessId);
    if (!apiKey) {
      throw new Error("No Resend API key configured (neither business-specific nor global RESEND_API_KEY)");
    }
    const resend = new Resend(apiKey);

    const html = buildInvoiceEmailTemplate({
      customerName,
      invoiceNumber,
      pdfUrl,
      grandTotal,
      orderId,
    });

    const result = await resend.emails.send({
      from,
      to,
      subject: `Invoice ${invoiceNumber} | AN Group`,
      html,
    });

    console.log(
      "RESEND SUCCESS",
      JSON.stringify(result, null, 2)
    );

    return {
      success: true,
      result,
    };

  } catch (err: any) {

    console.error(
      "RESEND ERROR",
      err
    );

    return {
      success: false,
      error:
        err?.message ||
        "Unknown email error",
    };
  }
}

/**
 * Generic HTML email sender, for callers with no dedicated template of
 * their own (e.g. the scheduled-report emailer) -- reuses the same
 * per-business-then-global Resend credential resolution as every other
 * sender here, so a scheduled report emails from this business's own
 * configured identity when it has one, same "work on their behalf"
 * pattern as the rest of this file.
 */
export async function sendGenericEmail({
  to,
  subject,
  html,
  businessId,
  templateKey,
  templateTokens,
}: {
  to: string | string[];
  subject: string;
  html: string;
  businessId?: string;
  /** When set, checks for a super-admin-saved override for this occasion
   * (see core/email/emailOccasions.ts) before falling back to the caller's
   * own subject/html -- lets call sites with no dedicated sender function
   * of their own (vendor application/approval, agreements, etc.) still be
   * admin-configurable through the same template system. */
  templateKey?: string;
  templateTokens?: Record<string, string>;
}) {
  try {
    let effectiveSubject = subject;
    let effectiveHtml = html;
    if (templateKey) {
      await connectDB();
      const override = await renderEmailTemplate(templateKey, templateTokens || {});
      if (override === "disabled") return { success: false, error: "Occasion disabled by admin" };
      if (override) {
        effectiveSubject = override.subject;
        effectiveHtml = override.html;
      }
    }

    const { apiKey, from } = await resolveResendCreds(businessId);
    if (!apiKey) {
      throw new Error("No Resend API key configured (neither business-specific nor global RESEND_API_KEY)");
    }
    const resend = new Resend(apiKey);
    const result = await resend.emails.send({ from, to, subject: effectiveSubject, html: effectiveHtml });
    return { success: true, result };
  } catch (err: any) {
    console.error("RESEND GENERIC EMAIL ERROR", err);
    return { success: false, error: err?.message || "Unknown email error" };
  }
}
