// Nav structure ONLY — no "use client" directive, deliberately. This data
// is imported by the server-side /api/ui/sidebar route as well as the
// client Sidebar component; when it lived inside sidebar.tsx (a client
// module), the RSC bundler handed the API route a client-reference proxy
// instead of the real array, so STATIC_MODULES.filter() threw at runtime
// and every sidebar load 500'd in production.
//
// TRIMMED FOR AN-CRM: this codebase started as a full copy of the ANgroup
// ERP app (see PROGRESS.md); AN-CRM is the standalone CRM product split out
// of it, covering the three operating modes -- Brand (multi-role, call
// center + appointments), SC (single-login work-order flow), POS
// (transactional storefront billing) -- so only CRM/Sales/Service-relevant
// nav entries are kept here. Manufacturing (Production), Purchase (supplier
// procurement), HR/Payroll, Growth (Social/AI Studio/Design Studio),
// Logistics, and the storefront-marketplace-specific admin screens/APIs/
// models (ecommerce Order, NativeProduct, ManufacturingBOM, VendorProduct
// wizard, B2B ordering, coupons, product categories, shipping) have been
// deleted outright (not just unlinked) -- this repo no longer contains
// that surface area at all, per explicit direction that AN-CRM be an
// independent, purpose-built product rather than a full ANgroup clone with
// unused modules left lying around.

// Restricts a nav item to specific operating modes -- e.g. Fault/Symptom/
// Solution masters and Workorders/Appointments make no sense for POS (pure
// billing counter, no workorders at all). Omitted entirely = visible under
// every mode (and for any business with no operatingMode set yet).
export type OperatingModeKey = "BRAND" | "SC" | "POS";

export interface NavItem {
  key: string; label: string; route: string; icon: string; modes?: OperatingModeKey[];
}
export interface NavSubGroup {
  key: string; label: string; items: NavItem[];
}
export interface NavGroup {
  label: string;
  items?: NavItem[];
  subgroups?: NavSubGroup[];
}

export const NAV_GROUPS: NavGroup[] = [
  { label: "Overview", items: [
    { key: "dashboard",  label: "Dashboard",    route: "/console",            icon: "LayoutDashboard" },
  ]},
  { label: "CRM", subgroups: [
    { key: "ppl-pipeline", label: "Sales Pipeline", items: [
      // Sales-opportunity pipeline, not applicable to SC (single-login
      // repair shop, workorders only -- no deals/leads concept there).
      { key: "deals", label: "Deals", route: "/console/deals", icon: "TrendingUp", modes: ["BRAND"] },
    ]},
    { key: "ppl-crm", label: "Calls & Workorders", items: [
      { key: "crm", label: "CRM Overview", route: "/console/crm", icon: "UserPlus" },
      // Gated on the CRM_CALLS.VIEW / CRM_JOBSHEETS.VIEW permission codes
      // auto-generated by syncPermissionsForModule once
      // /api/admin/seed-crm-modules has been run — see that route's top
      // comment. Keys match the ModuleDefinition.key values exactly
      // ("crm_calls", "crm_jobsheets") so isVisible()'s moduleKeys.has()
      // check lines up with what /api/ui/sidebar actually returns.
      // SC has no appointment pipeline at all -- everything there is a
      // workorder from intake onward, per explicit direction. BRAND keeps
      // the full Appointments flow.
      { key: "crm_calls",     label: "Appointments", route: "/console/crm/calls",     icon: "PhoneCall", modes: ["BRAND"] },
      { key: "crm_jobsheets", label: "Workorders",   route: "/console/crm/jobsheets", icon: "ClipboardList", modes: ["BRAND", "SC"] },
      // Shows every business's tickets by default (a filter dropdown on
      // the page itself narrows it down) rather than depending on the
      // sidebar's active-business switcher -- per explicit direction,
      // after that switcher was reported as unreliable.
      { key: "support_tickets", label: "Support Tickets", route: "/console/support-tickets", icon: "LifeBuoy" },
      // Public "Contact Us" page (app/contact/page.tsx) inbox -- gated on
      // the "contact_messages" permission module registered in
      // moduleHierarchy.ts alongside this page/its API route.
      { key: "contact-messages", label: "Contact Messages", route: "/console/contact-messages", icon: "MessageSquare" },
    ]},
  ]},
  { label: "Sales / POS", items: [
    // Quick-sale billing screen -- see admin/pos/page.tsx's top comment.
    { key: "pos",      label: "Point of Sale", route: "/console/pos",       icon: "ShoppingCart" },
    { key: "orders",   label: "Orders",       route: "/console/orders",     icon: "ShoppingBag" },
    { key: "sales",    label: "Sales",        route: "/console/sales",      icon: "TrendingUp" },
  ]},
  { label: "Materials & Inventory", items: [
    { key: "inventory",  label: "Inventory",    route: "/console/inventory",  icon: "Package" },
    { key: "warehouses", label: "Warehouses",   route: "/console/warehouses", icon: "Building2" },
    { key: "materials",  label: "Materials",    route: "/console/materials",  icon: "Box" },
    // Canonical Material/BOM list (Material Code/Description/Mode/SN/HSN/
    // Rate/Tax%), shared by Brand/SC/POS/Sales -- see models/BOM.ts and
    // this page's own top comment. Deliberately NOT /console/bom, which
    // still serves the unrelated OLD manufacturing BOM (models/
    // ManufacturingBOM.js, productVariantId/cost-rollup shape).
    { key: "material-catalog", label: "Material Catalog", route: "/console/material-catalog", icon: "Package" },
    { key: "masters-units",    label: "Units",              route: "/console/masters/units",              icon: "Ruler" },
    { key: "masters-brands",   label: "Brands & Models",    route: "/console/masters/brands",              icon: "Tags" },
    { key: "masters-catalog-requests", label: "Catalog Change Requests", route: "/console/masters/catalog-requests", icon: "ClipboardCheck" },
    { key: "masters-mat-cat",  label: "Material Categories",route: "/console/masters/material-categories", icon: "Layers" },
    // No workorders at all for POS (pure billing counter) -- so no fault/
    // symptom/solution diagnosis library or job-sheet options either.
    { key: "masters-fault-codes", label: "Fault Codes", route: "/console/masters/fault-codes", icon: "AlertTriangle", modes: ["BRAND", "SC"] },
    { key: "masters-symptom-codes", label: "Symptom Codes", route: "/console/masters/symptom-codes", icon: "AlertTriangle", modes: ["BRAND", "SC"] },
    { key: "masters-solutions",   label: "Solutions",   route: "/console/masters/solutions",   icon: "CheckCircle", modes: ["BRAND", "SC"] },
    { key: "masters-crm-options", label: "CRM Job Sheet Options", route: "/console/masters/crm-options", icon: "Settings", modes: ["BRAND", "SC"] },
    { key: "stock-transfers",   label: "Stock Transfers",   route: "/console/stock-transfers",   icon: "ArrowLeftRight" },
    { key: "stock-adjustments", label: "Stock Adjustments", route: "/console/stock-adjustments", icon: "SlidersHorizontal" },
    { key: "inventory-lots",    label: "Inventory Lots",    route: "/console/inventory/lots",    icon: "Box" },
  ]},
  { label: "Finance", items: [
    { key: "finance", label: "Finance", route: "/console/finance", icon: "DollarSign" },
  ]},
  { label: "Business", items: [
    { key: "businesses", label: "Businesses",   route: "/console/business",   icon: "Building2" },
    { key: "vendors",    label: "Vendors",      route: "/console/vendors",    icon: "Truck" },
    { key: "customers",  label: "Customer Data", route: "/console/customers", icon: "Users" },
  ]},
  { label: "Documents", items: [
    { key: "agreements",      label: "Agreements",      route: "/console/agreements",       icon: "FileSignature" },
    { key: "quotations",         label: "Quotations",         route: "/console/quotations",         icon: "FileText" },
    { key: "delivery-challans",  label: "Delivery Challans",  route: "/console/delivery-challans",  icon: "FileText" },
    { key: "credit-notes",       label: "Credit Notes",       route: "/console/credit-notes",       icon: "FileText" },
    { key: "debit-notes",        label: "Debit Notes",        route: "/console/debit-notes",        icon: "FileText" },
    { key: "proforma-invoices",  label: "Proforma Invoices",  route: "/console/proforma-invoices",  icon: "FileText" },
  ]},
  { label: "Reports", items: [
    { key: "reports",   label: "Reports & Downloads", route: "/console/reports",   icon: "BarChart3" },
    { key: "report-builder", label: "Report Builder", route: "/console/report-builder", icon: "BarChart3" },
    // Rebuilt on AN-CRM's own data (SalesInvoice/CrmCall/CrmJobSheet) --
    // the old version of this page/route was ecommerce-Order-based and
    // was removed along with the rest of the leftover ANgroup storefront
    // surface area; this is a fresh, CRM/POS-native replacement, not a
    // restoration of the old one.
    { key: "analytics", label: "Analytics",           route: "/console/analytics", icon: "BarChart3" },
  ]},
  { label: "Communication", items: [
    { key: "chat", label: "Team Chat", route: "/console/chat", icon: "MessageSquare" },
    // In-app product feedback -- any logged-in user, not admin-only (that's
    // the separate "Feedback" inbox under Admin > Configuration, which
    // reviews these submissions alongside customer contact-us ones).
    { key: "send-feedback", label: "Send Feedback", route: "/console/send-feedback", icon: "MessageSquare" },
    // Notifications is likewise no longer a page -- it's the floating
    // NotificationBell icon (top-right, every admin page).
    // ANu is the floating AnuWidget (see AdminShell.tsx), reachable from
    // every admin page, so it doesn't need a nav entry either.
  ]},
  // Only ever visible to a Super Admin on the AN-CRM platform business
  // itself -- a real tenant (Brand/SC/POS) never sees this group at all,
  // since it's gated on platform-level permission codes no tenant role is
  // ever granted. Trimmed from two lopsided subgroups (one 4-item, one
  // 10-item catch-all) down to three purpose-named ones -- Pincode Data
  // dropped from the nav entirely (it's reference data an import script
  // manages, not something anyone clicks into from here; the route/page
  // itself is untouched for anyone who still needs it directly).
  { label: "Admin", subgroups: [
    { key: "adm-users", label: "Users & Access", items: [
      { key: "admin-users",  label: "User Management",      route: "/console/users",  icon: "UserCog" },
      { key: "admin-access", label: "Access Control",       route: "/console/access", icon: "Key" },
      { key: "admin-roles",  label: "Roles & Permissions",  route: "/console/roles",  icon: "Shield" },
      { key: "admin-an-group-staff", label: "Platform Staff", route: "/console/an-group-staff", icon: "Shield" },
    ]},
    { key: "adm-system", label: "System", items: [
      // Being moved to Super-Admin-only, configured centrally per
      // business -- not shown to SC's single login.
      { key: "admin-intg", label: "Integrations", route: "/console/integrations", icon: "Plug", modes: ["BRAND", "POS"] },
      { key: "admin-status", label: "System Status", route: "/console/system-status", icon: "Activity" },
      { key: "admin-modules", label: "Modules", route: "/console/modules", icon: "Box" },
      { key: "admin-module-builder", label: "Module Builder", route: "/console/module-builder", icon: "LayoutTemplate" },
      { key: "admin-plan-features", label: "Plan Features", route: "/console/admin/plan-features", icon: "Sparkles" },
      { key: "admin-settings", label: "Settings", route: "/console/settings", icon: "Settings" },
      { key: "admin-plan", label: "Plan & Billing", route: "/console/plan", icon: "Receipt" },
      // SC-only in practice -- see /console/sub-accounts's own comment and
      // the scAllowedKeys gate in api/ui/sidebar/route.ts. Shown here in
      // the same "System" group as Plan & Billing since it's the same
      // billing-adjacent concern (paying to activate another account).
      { key: "sub-accounts", label: "SC Sub-Accounts", route: "/console/sub-accounts", icon: "Building2" },
    ]},
    { key: "adm-docs", label: "Documents & Billing", items: [
      { key: "admin-document-templates", label: "Document Templates", route: "/console/document-templates", icon: "FileText" },
      { key: "admin-invoice-templates", label: "Invoice Branding", route: "/console/invoice-templates", icon: "FileText" },
      { key: "admin-gst", label: "GST", route: "/console/gst", icon: "FileText" },
      { key: "admin-feedback", label: "Feedback", route: "/console/feedback", icon: "MessageSquare" },
      // Super Admin / AN Group only -- platform-wide bug reports and
      // enhancement requests (Send Feedback), not this-business-only
      // storefront contact-us submissions like the item above. The page
      // itself also gates on isSuperAdmin/isPlatformStaff.
      { key: "admin-product-feedback", label: "Product Feedback", route: "/console/admin/product-feedback", icon: "MessageSquare" },
      // Super Admin only -- the page and its API route both gate on
      // isSuperAdmin (see api/telegram/users/route.ts).
      { key: "admin-telegram-users", label: "Telegram Users", route: "/console/admin/telegram-users", icon: "Send" },
    ]},
  ]},
];

export const STATIC_MODULES = NAV_GROUPS.flatMap((g) =>
  g.items ? g.items : (g.subgroups ?? []).flatMap((sg) => sg.items)
);
