// Nav structure ONLY — no "use client" directive, deliberately. This data
// is imported by the server-side /api/ui/sidebar route as well as the
// client Sidebar component; when it lived inside sidebar.tsx (a client
// module), the RSC bundler handed the API route a client-reference proxy
// instead of the real array, so STATIC_MODULES.filter() threw at runtime
// and every sidebar load 500'd in production.
//
// TRIMMED FOR AN-CRM: this codebase started as a full copy of the ANgroup
// ERP app (see PROGRESS.md); AN-CRM is the standalone CRM product split out
// of it, covering the three operating modes -- Brand (multi-role, call
// center + appointments), SC (single-login work-order flow), POS
// (transactional storefront billing) -- so only CRM/Sales/Service-relevant
// nav entries are kept here. Manufacturing (Production), Purchase (supplier
// procurement), HR/Payroll, Growth (Social/AI Studio/Design Studio),
// Logistics, and the storefront-marketplace-specific admin screens/APIs/
// models (ecommerce Order, NativeProduct, ManufacturingBOM, VendorProduct
// wizard, B2B ordering, coupons, product categories, shipping) have been
// deleted outright (not just unlinked) -- this repo no longer contains
// that surface area at all, per explicit direction that AN-CRM be an
// independent, purpose-built product rather than a full ANgroup clone with
// unused modules left lying around.

export interface NavItem {
  key: string; label: string; route: string; icon: string;
}
export interface NavSubGroup {
  key: string; label: string; items: NavItem[];
}
export interface NavGroup {
  label: string;
  items?: NavItem[];
  subgroups?: NavSubGroup[];
}

export const NAV_GROUPS: NavGroup[] = [
  { label: "Overview", items: [
    { key: "dashboard",  label: "Dashboard",    route: "/admin",            icon: "LayoutDashboard" },
  ]},
  { label: "CRM", subgroups: [
    { key: "ppl-pipeline", label: "Sales Pipeline", items: [
      { key: "deals", label: "Deals", route: "/admin/deals", icon: "TrendingUp" },
    ]},
    { key: "ppl-crm", label: "Calls & Workorders", items: [
      { key: "crm", label: "CRM Overview", route: "/admin/crm", icon: "UserPlus" },
      // Gated on the CRM_CALLS.VIEW / CRM_JOBSHEETS.VIEW permission codes
      // auto-generated by syncPermissionsForModule once
      // /api/admin/seed-crm-modules has been run — see that route's top
      // comment. Keys match the ModuleDefinition.key values exactly
      // ("crm_calls", "crm_jobsheets") so isVisible()'s moduleKeys.has()
      // check lines up with what /api/ui/sidebar actually returns.
      { key: "crm_calls",     label: "Appointments", route: "/admin/crm/calls",     icon: "PhoneCall" },
      { key: "crm_jobsheets", label: "Workorders",   route: "/admin/crm/jobsheets", icon: "ClipboardList" },
      // Shows every business's tickets by default (a filter dropdown on
      // the page itself narrows it down) rather than depending on the
      // sidebar's active-business switcher -- per explicit direction,
      // after that switcher was reported as unreliable.
      { key: "support_tickets", label: "Support Tickets", route: "/admin/support-tickets", icon: "LifeBuoy" },
      // Public "Contact Us" page (app/contact/page.tsx) inbox -- gated on
      // the "contact_messages" permission module registered in
      // moduleHierarchy.ts alongside this page/its API route.
      { key: "contact-messages", label: "Contact Messages", route: "/admin/contact-messages", icon: "MessageSquare" },
    ]},
  ]},
  { label: "Sales / POS", items: [
    // Quick-sale billing screen -- see admin/pos/page.tsx's top comment.
    { key: "pos",      label: "Point of Sale", route: "/admin/pos",       icon: "ShoppingCart" },
    { key: "orders",   label: "Orders",       route: "/admin/orders",     icon: "ShoppingBag" },
    { key: "sales",    label: "Sales",        route: "/admin/sales",      icon: "TrendingUp" },
  ]},
  { label: "Materials & Inventory", items: [
    { key: "inventory",  label: "Inventory",    route: "/admin/inventory",  icon: "Package" },
    { key: "warehouses", label: "Warehouses",   route: "/admin/warehouses", icon: "Building2" },
    { key: "materials",  label: "Materials",    route: "/admin/materials",  icon: "Box" },
    // Canonical Material/BOM list (Material Code/Description/Mode/SN/HSN/
    // Rate/Tax%), shared by Brand/SC/POS/Sales -- see models/BOM.ts and
    // this page's own top comment. Deliberately NOT /admin/bom, which
    // still serves the unrelated OLD manufacturing BOM (models/
    // ManufacturingBOM.js, productVariantId/cost-rollup shape).
    { key: "material-catalog", label: "Material Catalog", route: "/admin/material-catalog", icon: "Package" },
    { key: "masters-units",    label: "Units",              route: "/admin/masters/units",              icon: "Ruler" },
    { key: "masters-brands",   label: "Brands & Models",    route: "/admin/masters/brands",              icon: "Tags" },
    { key: "masters-catalog-requests", label: "Catalog Change Requests", route: "/admin/masters/catalog-requests", icon: "ClipboardCheck" },
    { key: "masters-mat-cat",  label: "Material Categories",route: "/admin/masters/material-categories", icon: "Layers" },
    { key: "masters-fault-codes", label: "Fault Codes", route: "/admin/masters/fault-codes", icon: "AlertTriangle" },
    { key: "masters-symptom-codes", label: "Symptom Codes", route: "/admin/masters/symptom-codes", icon: "AlertTriangle" },
    { key: "masters-solutions",   label: "Solutions",   route: "/admin/masters/solutions",   icon: "CheckCircle" },
    { key: "masters-crm-options", label: "CRM Job Sheet Options", route: "/admin/masters/crm-options", icon: "Settings" },
    { key: "stock-transfers",   label: "Stock Transfers",   route: "/admin/stock-transfers",   icon: "ArrowLeftRight" },
    { key: "stock-adjustments", label: "Stock Adjustments", route: "/admin/stock-adjustments", icon: "SlidersHorizontal" },
    { key: "inventory-lots",    label: "Inventory Lots",    route: "/admin/inventory/lots",    icon: "Box" },
  ]},
  { label: "Finance", items: [
    { key: "finance", label: "Finance", route: "/admin/finance", icon: "DollarSign" },
  ]},
  { label: "Business", items: [
    { key: "businesses", label: "Businesses",   route: "/admin/business",   icon: "Building2" },
    { key: "vendors",    label: "Vendors",      route: "/admin/vendors",    icon: "Truck" },
    { key: "customers",  label: "Customer Data", route: "/admin/customers", icon: "Users" },
  ]},
  { label: "Documents", items: [
    { key: "agreements",      label: "Agreements",      route: "/admin/agreements",       icon: "FileSignature" },
    { key: "quotations",         label: "Quotations",         route: "/admin/quotations",         icon: "FileText" },
    { key: "delivery-challans",  label: "Delivery Challans",  route: "/admin/delivery-challans",  icon: "FileText" },
    { key: "credit-notes",       label: "Credit Notes",       route: "/admin/credit-notes",       icon: "FileText" },
    { key: "debit-notes",        label: "Debit Notes",        route: "/admin/debit-notes",        icon: "FileText" },
    { key: "proforma-invoices",  label: "Proforma Invoices",  route: "/admin/proforma-invoices",  icon: "FileText" },
  ]},
  { label: "Reports", items: [
    { key: "reports",   label: "Reports & Downloads", route: "/admin/reports",   icon: "BarChart3" },
    { key: "report-builder", label: "Report Builder", route: "/admin/report-builder", icon: "BarChart3" },
    // Rebuilt on AN-CRM's own data (SalesInvoice/CrmCall/CrmJobSheet) --
    // the old version of this page/route was ecommerce-Order-based and
    // was removed along with the rest of the leftover ANgroup storefront
    // surface area; this is a fresh, CRM/POS-native replacement, not a
    // restoration of the old one.
    { key: "analytics", label: "Analytics",           route: "/admin/analytics", icon: "BarChart3" },
  ]},
  { label: "Communication", items: [
    { key: "chat", label: "Team Chat", route: "/admin/chat", icon: "MessageSquare" },
    // In-app product feedback -- any logged-in user, not admin-only (that's
    // the separate "Feedback" inbox under Admin > Configuration, which
    // reviews these submissions alongside customer contact-us ones).
    { key: "send-feedback", label: "Send Feedback", route: "/admin/send-feedback", icon: "MessageSquare" },
    // Notifications is likewise no longer a page -- it's the floating
    // NotificationBell icon (top-right, every admin page).
    // ANu is the floating AnuWidget (see AdminShell.tsx), reachable from
    // every admin page, so it doesn't need a nav entry either.
  ]},
  // Only ever visible to a Super Admin on the AN-CRM platform business
  // itself -- a real tenant (Brand/SC/POS) never sees this group at all,
  // since it's gated on platform-level permission codes no tenant role is
  // ever granted. Trimmed from two lopsided subgroups (one 4-item, one
  // 10-item catch-all) down to three purpose-named ones -- Pincode Data
  // dropped from the nav entirely (it's reference data an import script
  // manages, not something anyone clicks into from here; the route/page
  // itself is untouched for anyone who still needs it directly).
  { label: "Admin", subgroups: [
    { key: "adm-users", label: "Users & Access", items: [
      { key: "admin-users",  label: "User Management",      route: "/admin/users",  icon: "UserCog" },
      { key: "admin-access", label: "Access Control",       route: "/admin/access", icon: "Key" },
      { key: "admin-roles",  label: "Roles & Permissions",  route: "/admin/roles",  icon: "Shield" },
      { key: "admin-an-group-staff", label: "Platform Staff", route: "/admin/an-group-staff", icon: "Shield" },
    ]},
    { key: "adm-system", label: "System", items: [
      { key: "admin-intg", label: "Integrations", route: "/admin/integrations", icon: "Plug" },
      { key: "admin-sso",  label: "SSO / Auth",   route: "/admin/sso",          icon: "Key" },
      { key: "admin-status", label: "System Status", route: "/admin/system-status", icon: "Activity" },
      { key: "admin-modules", label: "Modules", route: "/admin/modules", icon: "Box" },
      { key: "admin-settings", label: "Settings", route: "/admin/settings", icon: "Settings" },
      { key: "admin-plan", label: "Plan & Billing", route: "/admin/plan", icon: "Receipt" },
    ]},
    { key: "adm-docs", label: "Documents & Billing", items: [
      { key: "admin-document-templates", label: "Document Templates", route: "/admin/document-templates", icon: "FileText" },
      { key: "admin-invoice-templates", label: "Invoice Branding", route: "/admin/invoice-templates", icon: "FileText" },
      { key: "admin-gst", label: "GST", route: "/admin/gst", icon: "FileText" },
      { key: "admin-feedback", label: "Feedback", route: "/admin/feedback", icon: "MessageSquare" },
    ]},
  ]},
];

export const STATIC_MODULES = NAV_GROUPS.flatMap((g) =>
  g.items ? g.items : (g.subgroups ?? []).flatMap((sg) => sg.items)
);
